name: CI-stg

on:
  push:
    branches:
      - dev
  workflow_dispatch: # To create pipeline manually

jobs:
  build:
    runs-on: self-hosted
    environment: stg
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Fix permissions before checkout
        env:
          PC_SUDO_PASSWORD: ${{ vars.PC_SUDO_PASSWORD }}
        run: |
          echo "$PC_SUDO_PASSWORD" | sudo -S chown -R $USER:$USER $GITHUB_WORKSPACE || true
          echo "$PC_SUDO_PASSWORD" | sudo -S chmod -R u+rwX $GITHUB_WORKSPACE || true
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build the Docker image
        run: |
          docker pull ${{ vars.ENV_ECR }}
          docker build . --file build/Dockerfile --build-arg TAG=stg --tag ${{ vars.IMAGE_NAME }}
          docker push ${{ vars.IMAGE_NAME }}
  deploy:
    runs-on: self-hosted
    environment: stg
    needs: build
    env:
      TAG: stg
    steps:
      # Pull image and deploy. Usually, ECR and ENV_ECR has the same origin, therefore, just login to ECR.
      # If not, login to both ECR and ENV_ECR. I think so. And of course, AWS configure must be already configured before on the server
      - name: Deploy
        run: |
          aws ecr get-login-password | docker login -u AWS --password-stdin ${{ vars.ECR }}
          docker pull ${{ vars.ENV_ECR }}
          mkdir -p cosmo_agents_builder/frontend/${TAG}/docker
          docker cp $(docker create ${{ vars.ENV_ECR }}):/infra/frontend/cosmo-agents/${TAG}/docker-compose.yml cosmo_agents_builder/frontend/${TAG}/docker/docker-compose.yml
          docker cp $(docker create ${{ vars.ENV_ECR }}):/frontend/cosmo-agents/${TAG}/.env cosmo_agents_builder/frontend/${TAG}/.env
          docker compose -f cosmo_agents_builder/frontend/${TAG}/docker/docker-compose.yml down || true
          docker pull ${{ vars.IMAGE_NAME }};
          docker compose -f cosmo_agents_builder/frontend/${TAG}/docker/docker-compose.yml up -d
