name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: self-hosted
    environment: prod
    env:
      ECR_URL: ${{ secrets.ECR_URL }}
      BOT_PRIVATE_TOKEN: ${{ secrets.BOT_PRIVATE_TOKEN }}
      TAG: prod
      IMAGE_NAME: ${{ secrets.ECR_URL }}/cosmos-agent-frontend
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.17.0

      - name: Setup Node.js & pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.11.1

      - name: Fetch .env from GitLab
        run: |
          rm -rf .env
          sudo apt update -y && sudo apt install -y curl
          curl --header "PRIVATE-TOKEN: $BOT_PRIVATE_TOKEN" \
            "https://gitlab.rockitflow.com/api/v4/projects/1/repository/files/frontend%2Fcosmo-agents%2Fprod%2F.env/raw?ref=master" \
            > .env

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js
        run: pnpm run build

      - name: Configure Kaniko
        run: |
          mkdir -p ${{ runner.temp }}/kaniko/.docker
          echo '{"credsStore":"ecr-login"}' > ${{ runner.temp }}/kaniko/.docker/config.json

      - name: Build & Push Docker image (Kaniko)
        uses: addnab/docker-run-action@v3
        with:
          image: gcr.io/kaniko-project/executor:v1.10.0-debug
          options: >-
            -v ${{ github.workspace }}:/workspace
            -v ${{ runner.temp }}/kaniko/.docker:/kaniko/.docker
            -e IMAGE_NAME=${{ env.IMAGE_NAME }}
            -e TAG=${{ env.TAG }}
            -e BOT_PRIVATE_TOKEN=${{ env.BOT_PRIVATE_TOKEN }}
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            -e AWS_REGION=${{ env.AWS_REGION }}
          run: |
            /kaniko/executor \
              --context "/workspace" \
              --dockerfile "/workspace/build/Dockerfile" \
              --destination "${IMAGE_NAME}:${TAG}" \
              --build-arg BOT_PRIVATE_TOKEN=${BOT_PRIVATE_TOKEN}

      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-artifacts
      #     path: |
      #       .next/static
      #       .next/standalone
      #       build
      #     retention-days: 1

  # build_prod:
  #   name: build docker image
  #   runs-on: self-hosted
  #   needs: build_and_export
  #   environment: prod
  #   env:
  #     ECR_URL: ${{ secrets.ECR_URL }}
  #     BOT_PRIVATE_TOKEN: ${{ secrets.BOT_PRIVATE_TOKEN }}
  #     TAG: prod
  #     IMAGE_NAME: ${{ secrets.ECR_URL }}/cosmos-agent-frontend
  #     AWS_REGION: ${{ secrets.AWS_REGION }}
  #   steps:
  #     - name: Checkout source
  #       uses: actions/checkout@v4

  #     - name: Download build artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: build-artifacts
  #         path: .

  #     - name: Configure Kaniko
  #       run: |
  #         mkdir -p ${{ runner.temp }}/kaniko/.docker
  #         echo '{"credsStore":"ecr-login"}' > ${{ runner.temp }}/kaniko/.docker/config.json

  #     - name: Build & Push Docker image (Kaniko)
  #       uses: addnab/docker-run-action@v3
  #       with:
  #         image: gcr.io/kaniko-project/executor:v1.10.0-debug
  #         options: >-
  #           -v ${{ github.workspace }}:/workspace
  #           -v ${{ runner.temp }}/kaniko/.docker:/kaniko/.docker
  #           -e IMAGE_NAME=${{ env.IMAGE_NAME }}
  #           -e TAG=${{ env.TAG }}
  #           -e BOT_PRIVATE_TOKEN=${{ env.BOT_PRIVATE_TOKEN }}
  #           -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
  #           -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #           -e AWS_REGION=${{ env.AWS_REGION }}
  #         run: |
  #           /kaniko/executor \
  #             --context "/workspace" \
  #             --dockerfile "/workspace/build/Dockerfile" \
  #             --destination "${IMAGE_NAME}:${TAG}" \
  #             --build-arg BOT_PRIVATE_TOKEN=${BOT_PRIVATE_TOKEN}

  install_with_ssh_prod:
    name: deploy
    runs-on: self-hosted
    needs: build
    environment: prod
    env:
      ECR_URL: ${{ secrets.ECR_URL }}
      IMAGE_NAME: ${{ secrets.ECR_URL }}/cosmos-agent-frontend
      TAG: prod
      AWS_REGION: ${{ secrets.AWS_REGION }}
      SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
      SERVER_PROD: ${{ secrets.SERVER_PROD }}
      SSH_PRIVATE_KEY_ROCKSHIP: ${{ secrets.SSH_PRIVATE_KEY_ROCKSHIP }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Prepare SSH client
        run: |
          printf '%s\n' "$SUDO_PASSWORD" | sudo -S apt-get update -qq
          printf '%s\n' "$SUDO_PASSWORD" | sudo -S apt-get install -y -qq openssh-client

          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          touch ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

      - name: Deploy to production server
        run: |
          eval "$(ssh-agent -s)"
          ssh-add <(echo "${SSH_PRIVATE_KEY_ROCKSHIP}")

          ssh "$SERVER_PROD" "
            set -e
            aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_URL};
            docker pull ${IMAGE_NAME}:${TAG};
            docker stop prod_cosmos-frontend || true;
            docker rm prod_cosmos-frontend || true;
            docker run -d --name=prod_cosmos-frontend \
              -m 2G --memory-reservation 1700m \
              --network=nginx \
              --pull always \
              --restart unless-stopped \
              ${IMAGE_NAME}:${TAG};
            docker image prune -af;
          "
