'use client';

import { ContentLayout } from '@/components/nav/content-layout';
import { CosmoMark } from '@/components/nav/cosmo-mark';
import { PageHero } from '@/components/ui/page-hero';
import { Inbox } from 'lucide-react';
import WelcomeDialog from '@/components/tour/WelcomeDialog';
import { ResizablePanel, ResizablePanelGroup } from '@/components/ui/resizable';
import { Skeleton } from '@/components/ui/skeleton';
import { createTourCustomContent, TourStep, useTour } from '@/hooks/use-tour';
import { Agent } from '@/models/agent';
import { OnboardingPayload } from '@/models/auth';
import AgentApi from '@/network/client/agent';
import { useUser } from '@/hooks/use-user';
import classes from '@/styles/Inbox.module.css';
import {
  Accordion,
  AccordionControl,
  AccordionItem,
  AccordionPanel,
  Divider,
  Tabs,
  TabsList,
  TabsTab,
} from '@mantine/core';
import {
  Accessibility,
  ChevronDown,
  Mail,
  Send,
  Sparkles,
  Trash2,
} from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import { useEffect, useState } from 'react';
import { ConversationList } from './_components/conversation-list';
import { useConversation } from './use-conversation';

export default function InboxesPage() {
  const { user, invalidate } = useUser();
  const [, setConversation] = useConversation();
  const [activeTab, setActiveTab] = useState<string | null>(null);
  const [activeInboxes, setActiveInboxes] = useState<string[]>([]);

  const role = user?.roles?.[0]?.name || 'admin';

  const {
    data: agents,
    isLoading,
    isSuccess,
  } = useQuery({
    queryKey: ['agents'],
    queryFn: () => AgentApi.list({ filter_: {} }),
  });

  useEffect(() => {
    if (isSuccess && agents?.data?.list.length > 0) {
      const firstAgent = agents.data.list[0].entity;
      setActiveInboxes([firstAgent.id]);
      setActiveTab(`${firstAgent.id}.all_mails`);
    }
  }, [isSuccess, agents]);

  const data = agents?.data?.list.flatMap((item) => item.entity) || [];

  const handleOnTabChange = (tab: string | null) => {
    setActiveTab(tab);
    setConversation((prev) => ({ ...prev, selected: null }));
  };

  const items = data.map((agent) => (
    <AccordionItem key={agent.id} value={agent.id}>
      <AccordionControl>{agent.name}</AccordionControl>
      <AccordionPanel>
        <Tabs
          variant="pills"
          orientation="vertical"
          value={activeTab}
          onChange={handleOnTabChange}
        >
          <TabsList flex={1}>
            <TabsTab
              value={`${agent.id}.all_mails`}
              leftSection={<Mail width={20} height={20} strokeWidth={1.5} />}
            >
              All Mails
            </TabsTab>
            {role === 'admin' && (
              <>
                <Divider />
                <TabsTab
                  value={`${agent.id}.assign_to_ai`}
                  leftSection={
                    <Sparkles width={20} height={20} strokeWidth={1.5} />
                  }
                >
                  Assigned to AI
                </TabsTab>
              </>
            )}
            <TabsTab
              value={`${agent.id}.assign_to_human`}
              leftSection={
                <Accessibility width={20} height={20} strokeWidth={1.5} />
              }
            >
              Assigned to {role === 'admin' ? 'person' : 'me'}
            </TabsTab>
            <Divider />
            {role === 'admin' && (
              <TabsTab
                value={`${agent.id}.sent`}
                leftSection={<Send width={20} height={20} strokeWidth={1.5} />}
              >
                Sent
              </TabsTab>
            )}
            <TabsTab
              value={`${agent.id}.trash`}
              leftSection={<Trash2 width={20} height={20} strokeWidth={1.5} />}
            >
              Trash
            </TabsTab>
          </TabsList>
        </Tabs>
      </AccordionPanel>
    </AccordionItem>
  ));

  const [isTourOpen, setIsTourOpen] = useState(false);

  const tourDefaultSteps: TourStep[] = [
    {
      element: '#ai-inboxes-nav',
      popover: {
        title: '',
        side: 'right',
        description: '',
        customContent: createTourCustomContent({
          title: 'Handle Conversations with AI Agents',
          description:
            "View and reply to leads' messages generated by your AI agents during campaigns.",
          imageSrc: '',
          user,
        }),
      },
    },
    {
      element: '#campaigns-nav',
      popover: {
        title: '',
        side: 'right',
        description: '',
        customContent: createTourCustomContent({
          title: 'Automate Outreach at Scale',
          description:
            'Design message flows and assign AI agents to launch personalized outreach campaigns.',
          imageSrc: '',
          user,
        }),
      },
    },
    {
      element: '#all-prospects-nav',
      popover: {
        title: '',
        side: 'right',
        description: '',
        customContent: createTourCustomContent({
          title: 'Centralize Your Leads',
          description: 'Manage all contact data and sync with your CRM.',
          imageSrc: '',
          user,
        }),
      },
    },
    {
      element: '#libraries-nav',
      popover: {
        title: '',
        side: 'right',
        description: '',
        customContent: createTourCustomContent({
          title: 'Feed Your AI with Knowledge',
          description:
            'Upload documents and knowledge to train your AI agents.',
          imageSrc: '',
          user,
        }),
      },
    },
    {
      element: '#section-settings',
      popover: {
        title: '',
        side: 'right',
        description: '',
        customContent: createTourCustomContent({
          title: 'Configure Your AI Team',
          description:
            'Set up AI agents, your organization info, and advanced configurations.',
          imageSrc: '',
          user,
          update: invalidate,
        }),
      },
    },
  ];

  const { start, driver } = useTour(tourDefaultSteps, {
    onClickNext: () => driver?.moveNext(),
    onClickPrev: () => driver?.movePrevious(),
    onClickSkipAll: () => driver?.destroy(),
    onClickFinish: () => driver?.destroy(),
  });

  const tourEducationSteps: TourStep[] = [
    {
      element: '#ai-inboxes-nav',
      popover: {
        title: '',
        side: 'right',
        description: '',
        customContent: createTourCustomContent({
          title: 'Manage Student Conversations',
          description:
            'View and reply to messages from prospective students. AI Agents can handle FAQs or suggest courses.',
          imageSrc: '',
          user,
        }),
      },
    },
    {
      element: '#campaigns-nav',
      popover: {
        title: '',
        side: 'right',
        description: '',
        customContent: createTourCustomContent({
          title: 'Automate Course Promotion',
          description:
            'Set up campaigns to promote new courses or re-engage inactive learners using AI Agents.',
          imageSrc: '',
          user,
        }),
      },
    },
    {
      element: '#all-prospects-nav',
      popover: {
        title: '',
        side: 'right',
        description: '',
        customContent: createTourCustomContent({
          title: 'Import Student Leads',
          description:
            'Upload or sync student data from your CRM to manage outreach campaigns efficiently.',
          imageSrc: '',
          user,
        }),
      },
    },
    {
      element: '#libraries-nav',
      popover: {
        title: '',
        side: 'right',
        description: '',
        customContent: createTourCustomContent({
          title: 'Power AI with Your Course Content',
          description:
            'Upload syllabi, brochures, and course info so your AI can answer inquiries like a real advisor.',
          imageSrc: '',
          user,
        }),
      },
    },
    {
      element: '#section-settings',
      popover: {
        title: '',
        side: 'right',
        description: '',
        customContent: createTourCustomContent({
          title: 'Configure Your Education AI Agents',
          description:
            'Add AI Agents, define response behavior, and set up your organization profile for better targeting.',
          imageSrc: '',
          user,
          update: invalidate,
        }),
      },
    },
  ];

  const { start: startEducation, driver: driverEducation } = useTour(
    tourEducationSteps,
    {
      onClickNext: () => driverEducation?.moveNext(),
      onClickPrev: () => driverEducation?.movePrevious(),
      onClickSkipAll: () => driverEducation?.destroy(),
      onClickFinish: () => driverEducation?.destroy(),
    }
  );

  const tourHealthcareSteps: TourStep[] = [
    {
      element: '#ai-inboxes-nav',
      popover: {
        title: '',
        side: 'right',
        description: '',
        customContent: createTourCustomContent({
          title: 'Manage Patient Conversations',
          description:
            'View and respond to incoming messages from patients. AI Agents can handle appointment inquiries or follow-ups.',
          imageSrc: '',
          user,
        }),
      },
    },
    {
      element: '#campaigns-nav',
      popover: {
        title: '',
        side: 'right',
        description: '',
        customContent: createTourCustomContent({
          title: 'Automate Appointment & Service Reminders',
          description:
            'Set up campaigns to remind patients of upcoming visits, follow-ups, or introduce healthcare packages.',
          imageSrc: '',
          user,
        }),
      },
    },
    {
      element: '#all-prospects-nav',
      popover: {
        title: '',
        side: 'right',
        description: '',
        customContent: createTourCustomContent({
          title: 'Import Patient Records',
          description:
            'Upload or sync patient contact lists from your system to manage communication and segmentation.',
          imageSrc: '',
          user,
        }),
      },
    },
    {
      element: '#libraries-nav',
      popover: {
        title: '',
        side: 'right',
        description: '',
        customContent: createTourCustomContent({
          title: 'Feed AI with Your Service Information',
          description:
            'Upload health service packages, pricing, and insurance policies so AI can respond clearly and accurately.',
          imageSrc: '',
          user,
        }),
      },
    },
    {
      element: '#section-settings',
      popover: {
        title: '',
        side: 'right',
        description: '',
        customContent: createTourCustomContent({
          title: 'Configure Your Healthcare AI Agents',
          description:
            'Add and customize AI Agents, including tone and behavior, to best serve your patients and team.',
          imageSrc: '',
          user,
          update: invalidate,
        }),
      },
    },
  ];

  const { start: startHealthcare, driver: driverHealthcare } = useTour(
    tourHealthcareSteps,
    {
      onClickNext: () => driverHealthcare?.moveNext(),
      onClickPrev: () => driverHealthcare?.movePrevious(),
      onClickSkipAll: () => driverHealthcare?.destroy(),
      onClickFinish: () => driverHealthcare?.destroy(),
    }
  );

  const tourEstateSteps: TourStep[] = [
    {
      element: '#ai-inboxes-nav',
      popover: {
        title: '',
        side: 'right',
        description: '',
        customContent: createTourCustomContent({
          title: 'Manage Buyer Conversations',
          description:
            'View and reply to messages from potential buyers. AI Agents can recommend listings or answer property questions.',
          imageSrc: '',
          user,
        }),
      },
    },
    {
      element: '#campaigns-nav',
      popover: {
        title: '',
        side: 'right',
        description: '',
        customContent: createTourCustomContent({
          title: 'Automate Property Outreach',
          description:
            'Set up campaigns to follow up with leads, promote new listings, or nurture undecided buyers.',
          imageSrc: '',
          user,
        }),
      },
    },
    {
      element: '#all-prospects-nav',
      popover: {
        title: '',
        side: 'right',
        description: '',
        customContent: createTourCustomContent({
          title: 'Import Buyer Leads',
          description:
            'Upload or sync buyer information from your CRM to organize and personalize your communication.',
          imageSrc: '',
          user,
        }),
      },
    },
    {
      element: '#libraries-nav',
      popover: {
        title: '',
        side: 'right',
        description: '',
        customContent: createTourCustomContent({
          title: 'Upload Listings & Policies for AI',
          description:
            'Upload property listings, pricing, loan policies, and location details so AI can give accurate responses.',
          imageSrc: '',
          user,
        }),
      },
    },
    {
      element: '#section-settings',
      popover: {
        title: '',
        side: 'right',
        description: '',
        customContent: createTourCustomContent({
          title: 'Configure Your Real Estate AI Agents',
          description:
            'Add AI Agents and tailor their behavior to handle client inquiries or referrals across different listings.',
          imageSrc: '',
          user,
          update: invalidate,
        }),
      },
    },
  ];

  const { start: startEstate, driver: driverEstate } = useTour(
    tourEstateSteps,
    {
      onClickNext: () => driverEstate?.moveNext(),
      onClickPrev: () => driverEstate?.movePrevious(),
      onClickSkipAll: () => driverEstate?.destroy(),
      onClickFinish: () => driverEstate?.destroy(),
    }
  );

  useEffect(() => {
    (async () => {
      await invalidate();
    })();
  }, []);

  useEffect(() => {
    const ui_metadata = user?.ui_metadata as OnboardingPayload;
    if (user?.ui_metadata) {
      const onboarding = ui_metadata.onboarding;
      const status = ui_metadata.status;
      const onboarding_type = ui_metadata.onboarding_type;
      if (onboarding && status === 'not_started') {
        setIsTourOpen(true);
        return;
      }
      if (
        onboarding &&
        status === 'in_progress' &&
        onboarding_type === 'default'
      ) {
        start();
        return;
      }
      if (
        onboarding &&
        status === 'in_progress' &&
        onboarding_type === 'education'
      ) {
        startEducation();
        return;
      }
      if (
        onboarding &&
        status === 'in_progress' &&
        onboarding_type === 'estate'
      ) {
        startEstate();
        return;
      }
      if (
        onboarding &&
        status === 'in_progress' &&
        onboarding_type === 'healthcare'
      ) {
        startHealthcare();
        return;
      }
    }
  }, [user?.ui_metadata]);

  const handleExplore = () => {
    const onboarding_type = user?.ui_metadata?.onboarding_type;
    if (onboarding_type === 'default') {
      start();
    } else if (onboarding_type === 'education') {
      startEducation();
    } else if (onboarding_type === 'estate') {
      startEstate();
    } else if (onboarding_type === 'healthcare') {
      startHealthcare();
    }
    setIsTourOpen(false);
  };

  return (
    <ContentLayout
      title="AI Inboxes"
      section="Inbox"
      icon={Inbox}
    >
      <PageHero
        icon={Inbox}
        eyebrow="Inbox"
        accent="blue"
        title="AI Inboxes"
        description="Every inbound reply, classified by intent and paired with a draft you review before it goes out."
      />
      <ResizablePanelGroup
        autoSaveId="ai-inboxes"
        direction="horizontal"
        className="gap-4"
      >
        <ResizablePanel id="menu" order={1} defaultSize={15}>
          {isLoading ? (
            <div className="flex flex-col space-y-4">
              <Skeleton className="h-[50px] rounded-lg" />
              <Skeleton className="h-[50px] rounded-lg" />
              <Skeleton className="h-[50px] rounded-lg" />
              <Skeleton className="h-[50px] rounded-lg" />
              <Skeleton className="h-[50px] rounded-lg" />
            </div>
          ) : data.length > 0 ? (
            <Accordion
              value={activeInboxes}
              onChange={setActiveInboxes}
              multiple
              chevronPosition="right"
              chevron={<ChevronDown width={16} height={16} />}
              classNames={{
                label: classes.accordionLabel,
                control: classes.accordionControl,
                item: classes.accordionItem,
              }}
            >
              {items}
            </Accordion>
          ) : (
            <div className="flex h-full flex-1 items-center justify-center rounded-lg bg-zinc-100">
              <div className="flex flex-col items-center gap-4">
                <CosmoMark size={64} />
                <p className="text-muted-foreground">
                  Start creating your first campaign
                </p>
              </div>
            </div>
          )}
        </ResizablePanel>
        {activeTab && (
          <ResizablePanel id="conversation-list" order={2} defaultSize={85}>
            <ConversationList
              agent={
                data.find(
                  (item) => item.id === activeTab.split('.')[0]
                ) as Agent
              }
              tab={activeTab.split('.')[1]}
            />
          </ResizablePanel>
        )}
      </ResizablePanelGroup>
      <WelcomeDialog
        open={isTourOpen}
        description={
          <div className="text-center">
            Let's get started with your AI Agents!
          </div>
        }
        onExplore={handleExplore}
      />
    </ContentLayout>
  );
}
