version: "3"

volumes:
  prometheus-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:v2.37.9
    container_name: prometheus
    ports:
      - "9090:9090"
    command: "--config.file=/config/prometheus.yml"
    volumes:
      - ./prometheus.yml:/config/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    ports:
      - 9100:9100
    volumes:
      - /:/host:ro,rslave
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    restart: unless-stopped

  loki:
    container_name: loki
    image: grafana/loki:2.3.0
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./loki.yml:/config/loki.yml
      - ./loki/data:/data/loki
    command: -config.file=/config/loki.yml

  promtail:
    container_name: promtail
    image: grafana/promtail:2.3.0
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail.yml:/config/promtail.yml
    command: -config.file=/config/promtail.yml

  # grafana:
  #   container_name: grafana
  #   image: grafana/grafana:9.4.7
  #   ports:
  #     - "5000:3000"
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #     - ./grafana/provisioning:/etc/grafana/provisioning
  #   restart: unless-stopped
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #     - GF_USERS_ALLOW_SIGN_UP=false
  #   depends_on:
  #     - prometheus
